- id: markdowndocs
  name: markdowndocs
  description: "A lightweight md code documentation tool"
  entry: markdowndocs
  language: python
  language_version: python3
  require_serial: true
  types: [python]
