name: "ci-regression-tests"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  regression-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Run regression tests
        run: |
          poetry run pytest tests/test_regressions_markdowndocs.py -v
